apps/ads/urls.py
"""Точки входа для приложения ads"""

from django.urls import path

from apps.ads.views import (
    AdvertisementDeleteView,
    AdvertisementStaticsView,
    AdvertisementCreateView,
    AdvertisementUpdateView,
    AdvertisementListView,
    AdvertisementReadView,
)

app_name = "advertisement"

urlpatterns = [
    path("", AdvertisementListView.as_view(), name="advertisement_list"),
    path(
        "statistics",
        AdvertisementStaticsView.as_view(),
        name="advertisement_statistics",
    ),
    path("create/", AdvertisementCreateView.as_view(), name="advertisement_create"),
    path("<slug:pk>/", AdvertisementReadView.as_view(), name="advertisement_read"),
    path(
        "<slug:pk>/update/",
        AdvertisementUpdateView.as_view(),
        name="advertisement_update",
    ),
    path(
        "<slug:pk>/archive/",
        AdvertisementDeleteView.as_view(),
        name="advertisement_delete",
    ),
]

apps/core/urls.py
"""Точки входа для приложения Core"""

from django.urls import path

from apps.core.view import IndexView

app_name = "core"

urlpatterns = [
    path(
        "",
        IndexView.as_view(),
        name="index",
    ),
]

apps/lead/urls.py
"""Точки входа для приложения lead"""

from django.urls import path

from apps.lead.views import (
    LeadDeleteView,
    LeadCreateView,
    LeadUpdateView,
    LeadListView,
    LeadReadView,
)

app_name = "lead"

urlpatterns = [
    path("", LeadListView.as_view(), name="lead_list"),
    path("create/", LeadCreateView.as_view(), name="lead_create"),
    path("<slug:pk>/", LeadReadView.as_view(), name="lead_read"),
    path(
        "<slug:pk>/update/",
        LeadUpdateView.as_view(),
        name="lead_update",
    ),
    path(
        "<slug:pk>/archive/",
        LeadDeleteView.as_view(),
        name="lead_delete",
    ),
]

apps/product/urls.py
"""Точки входа для приложения Products"""

from django.urls import path

from apps.product.views import (
    ProductListView,
    ProductCreateView,
    ProductDeleteView,
    ProductUpdateView,
    ProductReadView,
)

app_name = "product"

urlpatterns = [
    path("", ProductListView.as_view(), name="products_list"),
    path("create/", ProductCreateView.as_view(), name="product_create"),
    path("<slug:pk>/", ProductReadView.as_view(), name="product_read"),
    path("<slug:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("<slug:pk>/archive/", ProductDeleteView.as_view(), name="product_delete"),
]

config/urls.py
"""
Основная точка входа в проект, содержит стартовые urls
"""

from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.core.urls")),
    path("account/", include("apps.account.urls")),
    path("product/", include("apps.product.urls")),
    path("advertisement/", include("apps.ads.urls")),
    path("lead/", include("apps.lead.urls")),
    path("contract/", include("apps.contract.urls")),
]

if settings.DEBUG:
    urlpatterns.append(path("__debug__", include("debug_toolbar.urls")))

apps/ads/models.py
"""Модуль с моделями приложения ads"""

from django.db.models import (
    Model,
    CharField,
    ForeignKey,
    DO_NOTHING,
    DecimalField,
    BooleanField,
)

from apps.product.models import Product


class Advertisement(Model):
    name = CharField(primary_key=True, max_length=128, verbose_name="Название")
    product = ForeignKey(Product, verbose_name="Услуга", on_delete=DO_NOTHING)
    channel = CharField(max_length=255, verbose_name="Канал продвижения")
    cost = DecimalField(max_digits=16, decimal_places=2, verbose_name="Бюджет")
    archived = BooleanField(default=0, verbose_name="В архиве")

    def __str__(self):
        return f"Advertisement {self.name!r}"

apps/core/models.py
"""Модуль с моделями приложения core"""

from json import loads

from django.db.models import BooleanField, Model, PositiveIntegerField


class SiteSettings(Model):
    cache_active = BooleanField(
        default=False,
    )
    cache_time = PositiveIntegerField(
        default=60 * 60 * 24,
    )  # sec*min*hor

    def save(self, *args, **kwargs):
        self.__class__.objects.exclude(id=self.id).delete()
        if not self.cache_active:
            self.cache_time = 0
        super().save(*args, **kwargs)

    @classmethod
    def load(cls):
        try:
            return cls.objects.get()
        except cls.DoesNotExist:
            return cls()

    @staticmethod
    def load_config():
        with open("core/config/config.json", "r") as cfg:
            data = loads(cfg.read())
            model = SiteSettings.objects.get()
            model.cache_active = data["cache_active"]
            model.cache_time = data["cache_time"]
            model.save()

    def __str__(self):
        return "Настройки сайта"

apps/core/forms.py
"""Модуль конструктора формам для приложения Core"""

templates/core/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>CRM</title>
</head>
<body>

<div class="main-container d-flex">
    <div class="sidebar" id="side_nav">
        <div class="header-box px-3 pt-4 pb-4">
            <h1 class="fs-4 nav-logo">
                <span class="text-black text-uppercase font-weight-bold">
                    <a class="link-dark text-decoration-none" href="/">CRM BACKOFFICE</a>
                </span>
            </h1>
        </div>
        <ul class="list-unstyled px-2">
            {% if 'view_product' in perms %}
            <li><a href="{%url 'product:products_list'%}" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-microchip"></i></span><span class="ml-1"> Услуги</span>
            </a></li>
            {% endif %}
            {% if perms.advertisements.view_advertisement %}
            <li><a href="{% url 'advertisement:advertisement_list' %}" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-ad"></i></span><span class="ml-1"> Рекламные компании</span>
            </a></li>
            {% endif %}
            {% if perms.leads.view_lead %}
            <li><a href="/leads/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-user-clock"></i></span><span class="px-1"> Лиды</span>
            </a></li>
            {% endif %}
            {% if perms.contracts.view_contract %}
            <li><a href="/contracts/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-file-alt"></i></span><span class="px-1"> Контракты</span>
            </a></li>
            {% endif %}
            {% if perms.customers.view_customer %}
            <li><a href="/customers/" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-user-check"></i></span><span class="px-1"> Активные клиенты</span>
            </a></li>
            {% endif %}
            <li>
                <hr>
            </li>
            <li><a href="/accounts/logout" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-sign-out-alt"></i></span><span class="px-1"> Выход</span>
            </a></li>
        </ul>
    </div>
    <div class="content px-3 pt-4">
        {% block content %}{% endblock %}
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/core/index.html
{% extends "core/_base.html" %}

{% block content %}
<h2 class="fw-bold">Общая статистика</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col">
        <div class="card border-light shadow" style="background: #eee">
            <div class="card-body bg-gray-900">
                <h5 class="card-title fw-bold">
                    <a href="{% url 'product:products_list' %}" class="link-dark text-decoration-none">Услуг</a>
                </h5>
                <i class="fas fa-microchip float-end"></i>
                <p class="card-text fw-bold fs-1">{{ products_count }}</p>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card border-light shadow" style="background: #eee">
            <div class="card-body">
                <h5 class="card-title fw-bold">
                    <a href="{% url 'advertisement:advertisement_list' %}" class="link-dark text-decoration-none">Рекламных компаний</a>
                </h5>
                <i class="fas fa-ad float-end"></i>
                <p class="card-text fw-bold fs-1">{{ advertisements_count }}</p>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card border-light shadow" style="background: #eee">
            <div class="card-body">
                <h5 class="card-title fw-bold">
                    <a href="{% url 'lead:lead_list' %}" class="link-dark text-decoration-none">Лидов</a>
                </h5>
                <i class="fas fa-user-clock float-end"></i>
                <p class="card-text fw-bold fs-1">{{ leads_count }}</p>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card border-light shadow">
            <div class="card-body" style="background: #eee">
                <h5 class="card-title fw-bold">
                    <a href="/customers/" class="link-dark text-decoration-none">Активных клиентов</a>
                </h5>
                <i class="fas fa-user-check float-end"></i>
                <p class="card-text fw-bold fs-1">{{ customers_count }}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}