apps/core/urls.py
"""Точки входа для приложения Core"""

from django.urls import path

from apps.core.view import IndexView

app_name = "core"

urlpatterns = [
    path(
        "",
        IndexView.as_view(),
        name="index",
    ),
]

apps/product/urls.py
"""Точки входа для приложения Products"""

from django.urls import path

from apps.product.views import (
    ProductListView,
    ProductCreateView,
    ProductDeleteView,
    ProductUpdateView,
    ProductReadView,
)

app_name = "product"

urlpatterns = [
    path("", ProductListView.as_view(), name="products_list"),
    path("create/", ProductCreateView.as_view(), name="product_create"),
    path("<slug:pk>/", ProductReadView.as_view(), name="product_read"),
    path("<slug:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("<slug:pk>/archive/", ProductDeleteView.as_view(), name="product_delete"),
]

config/urls.py
"""
Основная точка входа в проект, содержит стартовые urls
"""

from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.core.urls")),
    path("account/", include("apps.account.urls")),
    path("product/", include("apps.product.urls")),
    path("advertisement/", include("apps.ads.urls")),
    path("lead/", include("apps.lead.urls")),
    path("contract/", include("apps.contract.urls")),
]

if settings.DEBUG:
    urlpatterns.append(path("__debug__", include("debug_toolbar.urls")))

apps/product/models.py
"""Модуль с моделями приложения product"""

from django.db.models import Model, CharField, TextField, DecimalField, BooleanField


class Product(Model):
    name = CharField(primary_key=True, max_length=128, verbose_name="Название")
    price = DecimalField(max_digits=16, decimal_places=2, verbose_name="Стоимость")
    description = TextField(verbose_name="Описание")
    archived = BooleanField(default=0, verbose_name="В архиве")

    def __str__(self):
        return f"Product {self.name!r}"

apps/product/forms.py
"""Модуль конструктора формам для приложения products"""

apps/product/views.py
"""Модуль контроллер для приложения products"""

from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import (
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
    ListView,
)

from apps.product.models import Product
from django.contrib.auth.mixins import UserPassesTestMixin


class ProductView(View):
    model = Product

    context_object_name = "product"
    fields = (
        "name",
        "price",
        "description",
        "is_active",
    )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["perms"] = list(
            permission.codename for permission in self.request.user.permissions
        )
        return context

    def check_permission(self, codename):
        if self.request.user.is_superuser:
            return True
        return any(
            permission.codename == codename
            for permission in self.request.user.permissions
        )


class ProductCreateView(UserPassesTestMixin, ProductView, CreateView):
    template_name_suffix = "_create"
    success_url = reverse_lazy("product:product_read")

    def get_success_url(self):
        return reverse(
            "product:product_read",
            kwargs={"pk": self.object.pk},
        )

    def test_func(self):
        return self.check_permission("add_product")


class ProductReadView(UserPassesTestMixin, ProductView, DetailView):
    def test_func(self):
        return self.check_permission("view_product")


class ProductUpdateView(UserPassesTestMixin, ProductView, UpdateView):
    success_url = reverse_lazy("product:product_read")
    template_name_suffix = "_update"

    def get_success_url(self):
        return reverse(
            "product:product_read",
            kwargs={"pk": self.object.pk},
        )

    def test_func(self):
        return self.check_permission("change_product")


class ProductDeleteView(UserPassesTestMixin, ProductView, DeleteView):

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)

    def get_success_url(self):
        return reverse(
            "product:products_list",
        )

    def test_func(self):
        return self.check_permission("delete_product")


class ProductListView(UserPassesTestMixin, ProductView, ListView):
    queryset = Product.objects.filter(archived=False)
    context_object_name = "products"

    def test_func(self):
        return self.check_permission("view_product")

templates/product/product_confirm_delete.html
{% extends 'core/_base.html' %}


{% block content %}
<h2 class="fw-bold">Действительно хотите удалить услугу: {{ product.name }}?</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col">{{ product.name }}</div>
    <div class="col">{{ product.description }}</div>
    <div class="col">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Удалить услугу</button>
        </form>
    </div>
</div>
<div class="col">
    <a href="{% url 'product:product_read' pk=product.pk %}" class="btn btn-primary"
    >К Услуге</a>
</div>
<div class="col">
    <a href="{% url 'product:products_list' %}"  class="btn btn-primary"
    >К списку услуг</a>
</div>
{% endblock %}

templates/product/product_create.html
{% extends "core/_base.html" %}

{% block content %}
<h2 class="fw-bold">Создание услуги</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Создать</button>
        </form>
    </div>
    <div class="col"></div>
</div>
<a href="{%url 'product:products_list'%}" class="btn btn-primary">К списку услуг</a>
{% endblock %}

templates/product/product_delete.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Удаление услуги</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <p>Вы уверены, что хотите удалить "{{ product.name }}"?</p>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

templates/product/product_detail.html
{% extends "core/_base.html" %}

{% block content %}
<h2 class="fw-bold">Детальная информация об услуге</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <div class="card border-dark shadow" style="background: #eee">
            <div class="card-body">
                <h5 class="card-title fw-bold">{{ product.name }}</h5>
                <p class="card-text">{{ product.description }}</p>
                <div class="d-flex justify-content-end fw-bold">{{ object.price }}руб</div>
                <div class="d-flex justify-content-center fw-bold">
                    <a href="{% url 'product:product_update' pk=product.pk %}" class="btn btn-primary">Редактировать</a>
                </div>
                <a href="{% url 'product:product_delete' pk=product.pk %}" class="btn btn-danger">Удалить услугу</a>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
<a href="{%url 'product:products_list'%}" class="btn btn-primary">К списку услуг</a>

{% endblock %}

templates/product/product_list.html
{% extends "core/_base.html" %}

{% block content %}
<h2 class="fw-bold">Услуги</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="hstack gap-3 pb-4">
        <a href="{% url 'product:product_create' %}" class="btn btn-success p-2">Создать</a>
    </div>
    <div class="col">
        <ul class="list-group">
            {% for product in products %}
            <li class="list-group-item list-group-item-light d-flex justify-content-between">
                <a href="{% url 'product:product_read' pk=product.pk %}" class="text-decoration-none link-dark">{{ product.name }}</a>
                <a href="{% url 'product:product_delete' pk=product.pk %}" class="btn btn-danger">Удалить</a>
            </li>
            {% empty %}
            <p>Нет активных услуг</p>
            {% endfor %}
        </ul>
    </div>

</div>

<a href="{%url 'core:index'%}" class="btn btn-primary">На главную</a>

{% endblock %}

templates/product/product_update.html
{% extends "core/_base.html" %}

{% block content %}
<h2 class="fw-bold">Редактирование услуги</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Применить</button>
        </form>
    </div>
    <div class="col"></div>
</div>
<div class="d-flex justify-content-center fw-bold">
                    <a href="{% url 'product:product_read' pk=product.pk %}" class="btn btn-primary">К услуге</a>
                </div>

{% endblock %}

templates/product/products-create.html
{% extends "core/_base.html" %}

{% block content %}
<h2 class="fw-bold">Создание услуги</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST" action="/products/new/">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Создать</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

templates/product/products-detail.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Детальная информация об услуге</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <div class="card border-dark shadow" style="background: #eee">
            <div class="card-body">
                <h5 class="card-title fw-bold">{{ object.name }}</h5>
                <p class="card-text">{{ object.description }}</p>
                <div class="d-flex justify-content-end fw-bold">{{ object.cost }}руб</div>
                <div class="d-flex justify-content-center fw-bold">
                    <a href="/products/{{ object.pk }}/edit" class="btn btn-primary">Редактировать</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

templates/product/products-edit.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Редактирование услуги</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST" action="/products/{{ object.pk }}/edit/">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Применить</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}