apps/ads/urls.py
"""Точки входа для приложения ads"""

from django.urls import path

from apps.ads.views import (
    AdvertisementDeleteView,
    AdvertisementStaticsView,
    AdvertisementCreateView,
    AdvertisementUpdateView,
    AdvertisementListView,
    AdvertisementReadView,
)

app_name = "advertisement"

urlpatterns = [
    path("", AdvertisementListView.as_view(), name="advertisement_list"),
    path(
        "statistics",
        AdvertisementStaticsView.as_view(),
        name="advertisement_statistics",
    ),
    path("create/", AdvertisementCreateView.as_view(), name="advertisement_create"),
    path("<slug:pk>/", AdvertisementReadView.as_view(), name="advertisement_read"),
    path(
        "<slug:pk>/update/",
        AdvertisementUpdateView.as_view(),
        name="advertisement_update",
    ),
    path(
        "<slug:pk>/archive/",
        AdvertisementDeleteView.as_view(),
        name="advertisement_delete",
    ),
]

apps/core/urls.py
"""Точки входа для приложения Core"""

from django.urls import path

from apps.core.view import IndexView

app_name = "core"

urlpatterns = [
    path(
        "",
        IndexView.as_view(),
        name="index",
    ),
]

config/urls.py
"""
Основная точка входа в проект, содержит стартовые urls
"""

from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.core.urls")),
    path("account/", include("apps.account.urls")),
    path("product/", include("apps.product.urls")),
    path("advertisement/", include("apps.ads.urls")),
    path("lead/", include("apps.lead.urls")),
    path("contract/", include("apps.contract.urls")),
]

if settings.DEBUG:
    urlpatterns.append(path("__debug__", include("debug_toolbar.urls")))

apps/ads/models.py
"""Модуль с моделями приложения ads"""

from django.db.models import (
    Model,
    CharField,
    ForeignKey,
    DO_NOTHING,
    DecimalField,
    BooleanField,
)

from apps.product.models import Product


class Advertisement(Model):
    name = CharField(primary_key=True, max_length=128, verbose_name="Название")
    product = ForeignKey(Product, verbose_name="Услуга", on_delete=DO_NOTHING)
    channel = CharField(max_length=255, verbose_name="Канал продвижения")
    cost = DecimalField(max_digits=16, decimal_places=2, verbose_name="Бюджет")
    archived = BooleanField(default=0, verbose_name="В архиве")

    def __str__(self):
        return f"Advertisement {self.name!r}"

apps/ads/forms.py
"""Модуль конструктор форм приложения ads"""

from django import forms
from apps.ads.models import Advertisement


class AdvertisementForm(forms.ModelForm):
    class Meta:
        model = Advertisement
        fields = ["name", "product", "channel", "cost"]

apps/ads/views.py
"""Модуль контроллер для приложения ads"""

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import (
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
    ListView,
)

from apps.ads.forms import AdvertisementForm
from apps.ads.models import Advertisement


# TODO Проверить разрешения - везде add_advertisement


class AdvertisementView(View):
    queryset = Advertisement.objects.select_related("product")
    context_object_name = "advertisement"

    def check_permission(self, codename):
        if self.request.user.is_superuser:
            return True
        return any(
            permission.codename == codename
            for permission in self.request.user.permissions
        )


class AdvertisementCreateView(AdvertisementView, CreateView):
    form_class = AdvertisementForm
    template_name = "ads/advertisement_create.html"

    def get_success_url(self):
        return reverse(
            "advertisement:advertisement_read",
            kwargs={"pk": self.object.pk},
        )


class AdvertisementReadView(AdvertisementView, DetailView):
    template_name_suffix = "_read"

    def test_func(self):
        return self.check_permission("add_advertisement")


class AdvertisementUpdateView(AdvertisementView, UpdateView):
    success_url = reverse_lazy("advertisement:advertisement_read")
    template_name_suffix = "_update"
    form_class = AdvertisementForm

    def get_success_url(self):
        return reverse(
            "advertisement:advertisement_read",
            kwargs={"pk": self.object.pk},
        )

    def test_func(self):
        return self.check_permission("add_advertisement")


class AdvertisementDeleteView(AdvertisementView, DeleteView):
    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)

    def get_success_url(self):
        return reverse(
            "advertisement:advertisement_list",
        )

    def test_func(self):
        return self.check_permission("add_advertisement")


class AdvertisementListView(AdvertisementView, ListView):
    queryset = Advertisement.objects.filter(archived=False).only("name")
    context_object_name = "advertisements"

    def test_func(self):
        return self.check_permission("add_advertisement")


class AdvertisementStaticsView(AdvertisementView):
    #  TODO заполнить context
    def get(self, request, *args, **kwargs):
        return render(
            request,
            "ads/advertisement_statistics.html",
            # {
            # ...
            # },
        )

    def test_func(self):
        return self.check_permission("add_advertisement")

templates/ads/ads-create.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Создание рекламной компании</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST" action="/ads/new/">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Создать</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

templates/ads/ads-delete.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Удаление рекламной компании</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <p>Вы уверены что хотите удалить "{{ object.name }}"?</p>
        <form method="POST" action="/ads/{{ object.pk }}/delete/">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

templates/ads/ads-detail.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Детальная информация о рекламной компании</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <div class="card border-dark shadow" style="background: #eee">
            <div class="card-body">
                <h5 class="card-title fw-bold">{{ object.name }}</h5>
                <p class="card-text">{{ object.product.name }}</p>
                <div class="d-flex justify-content-end fw-bold">{{ object.budget }}руб</div>
                <div class="d-flex justify-content-center fw-bold">
                    <a href="/ads/{{ object.pk }}/edit" class="btn btn-primary">Редактировать</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

templates/ads/ads-edit.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Редактирование рекламной компании</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST" action="/ads/{{ object.pk }}/edit/">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Применить</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

templates/ads/ads-statistic.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Статистика рекламных компаний</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col">
        <ul class="list-group">
            {% for ad in ads %}
            <li class="list-group-item list-group-item-light d-flex justify-content-between">
                <a href="/ads/{{ ad.pk }}" class="text-decoration-none link-dark">{{ ad.name }}</a>
                <p>Лидов: {{ ad.leads_count }} | Активных клиентов: {{ ad.customers_count }} | Соотношение контрактов к затратам: {{ ad.profit|default_if_none:"-" }}</p>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

templates/ads/advertisement_confirm_delete.html
{% extends 'core/_base.html' %}


{% block content %}
<h2 class="fw-bold">Действительно хотите удалить услугу: {{ advertisement.name }}?</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <p class="card-text">{{ advertisement.name }}</p>
    <p class="card-text">{{ advertisement.channel }}</p>
    <p class="card-text">{{ advertisement.cost }}</p>
    <p class="card-text">{{ advertisement.product.name }}</p>
    <div class="col">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Удалить услугу</button>
        </form>
    </div>
</div>
<div class="col">
    <a href="{% url 'advertisement:advertisement_read' pk=advertisement.pk %}" class="btn btn-primary"
    >К Услуге</a>
</div>
<div class="col">
    <a href="{% url 'advertisement:advertisement_list' %}" class="btn btn-primary">К списку услуг</a>
</div>
{% endblock %}

templates/ads/advertisement_create.html
{% extends "core/_base.html" %}

{% block content %}
<h2 class="fw-bold">Создание рекламной компании</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Создать</button>
        </form>
    </div>
    <div class="col"></div>
</div>
<a href="{%url 'advertisement:advertisement_list'%}" class="btn btn-primary">К списку рекламных программ</a>
{% endblock %}

templates/ads/advertisement_delete.html
{% extends "core/_base.html" %}

{% block content %}
<h2 class="fw-bold">Удаление рекламной компании</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <p>Вы уверены, что хотите удалить "{{ advertisement.name }}"?</p>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

templates/ads/advertisement_list.html
{% extends "core/_base.html" %}

{% block content %}
<h2 class="fw-bold">Рекламные компании</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="hstack gap-3 pb-4">
        <a href="{% url 'advertisement:advertisement_create' %}" class="btn btn-success p-2">Создать</a>
        <a href="{% url 'advertisement:advertisement_statistics' %}" class="btn btn-primary p-2">Статистика</a>
    </div>
    <div class="col">
        <ul class="list-group">
            {% for advertisement in advertisements %}
            <li class="list-group-item list-group-item-light d-flex justify-content-between">
                <a href="{% url 'advertisement:advertisement_read' pk=advertisement.pk %}" class="text-decoration-none link-dark">{{ advertisement.name }}</a>
                <a href="{% url 'advertisement:advertisement_delete' pk=advertisement.pk %}" class="btn btn-danger">Удалить</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
<a href="{%url 'core:index'%}" class="btn btn-primary">На главную</a>

{% endblock %}

templates/ads/advertisement_read.html
{% extends "core/_base.html" %}

{% block content %}
<h2 class="fw-bold">Детальная информация о рекламной компании</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <div class="card border-dark shadow" style="background: #eee">
            <div class="card-body">
                <h5 class="card-title fw-bold">{{ advertisement.name }}</h5>
                <p class="card-text">{{ advertisement.product.name }}</p>
                <p class="card-text">{{ advertisement.channel }}</p>
                <div class="d-flex justify-content-end fw-bold">{{ advertisement.cost }}руб</div>
                <div class="d-flex justify-content-center fw-bold">
                    <a href="{% url 'advertisement:advertisement_update' pk=advertisement.pk %}" class="btn btn-primary">Редактировать</a>
                </div>
                <div class="d-flex justify-content-center fw-bold">
                <a href="{% url 'advertisement:advertisement_delete' pk=advertisement.pk %}" class="btn btn-danger">Удалить услугу</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
<a href="{%url 'advertisement:advertisement_list'%}" class="btn btn-primary">К списку рекламных программ</a>

{% endblock %}

templates/ads/advertisement_statistic.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Статистика рекламных компаний</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col">
        <ul class="list-group">
            {% for ad in ads %}
            <li class="list-group-item list-group-item-light d-flex justify-content-between">
                <a href="/ads/{{ ad.pk }}" class="text-decoration-none link-dark">{{ ad.name }}</a>
                <p>Лидов: {{ ad.leads_count }} | Активных клиентов: {{ ad.customers_count }} | Соотношение контрактов к затратам: {{ ad.profit|default_if_none:"-" }}</p>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

templates/ads/advertisement_statistics.html
{% extends "core/_base.html" %}

{% block content %}
<h2 class="fw-bold">Статистика рекламных компаний</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col">
        <ul class="list-group">
            {% for ad in ads %}
            <li class="list-group-item list-group-item-light d-flex justify-content-between">
                <a href="{% url 'advertisement:advertisement_read' pk=advertisement.pk %}" class="text-decoration-none link-dark">{{ ad.name }}</a>
                <p>Лидов: {{ ad.leads_count }} | Активных клиентов: {{ ad.customers_count }} | Соотношение контрактов к затратам: {{ ad.profit|default_if_none:"-" }}</p>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
<a href="{%url 'advertisement:advertisement_list'%}" class="btn btn-primary">К списку рекламных программ</a>
{% endblock %}

templates/ads/advertisement_update.html
{% extends "core/_base.html" %}

{% block content %}
<h2 class="fw-bold">Редактирование рекламной компании</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Применить</button>
        </form>
    </div>
    <div class="col"></div>
</div>
<a href="{% url 'advertisement:advertisement_read' pk=advertisement.pk %}" class="btn btn-primary">Сохранить без изменений</a>
<a href="{%url 'advertisement:advertisement_list'%}" class="btn btn-primary">К списку рекламных программ</a>

{% endblock %}