apps/lead/urls.py
"""Точки входа для приложения lead"""

from django.urls import path

from apps.lead.views import (
    LeadDeleteView,
    LeadCreateView,
    LeadUpdateView,
    LeadListView,
    LeadReadView,
)

app_name = "lead"

urlpatterns = [
    path("", LeadListView.as_view(), name="lead_list"),
    path("create/", LeadCreateView.as_view(), name="lead_create"),
    path("<slug:pk>/", LeadReadView.as_view(), name="lead_read"),
    path(
        "<slug:pk>/update/",
        LeadUpdateView.as_view(),
        name="lead_update",
    ),
    path(
        "<slug:pk>/archive/",
        LeadDeleteView.as_view(),
        name="lead_delete",
    ),
]

config/urls.py
"""
Основная точка входа в проект, содержит стартовые urls
"""

from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.core.urls")),
    path("account/", include("apps.account.urls")),
    path("product/", include("apps.product.urls")),
    path("advertisement/", include("apps.ads.urls")),
    path("lead/", include("apps.lead.urls")),
    path("contract/", include("apps.contract.urls")),
]

if settings.DEBUG:
    urlpatterns.append(path("__debug__", include("debug_toolbar.urls")))

apps/lead/models.py
"""Модуль с моделями приложения lead"""

import uuid

from django.core.validators import RegexValidator
from django.db.models import (
    Model,
    CharField,
    ForeignKey,
    DO_NOTHING,
    UUIDField,
    EmailField,
    BooleanField,
)

from apps.ads.models import Advertisement


class Lead(Model):
    id = UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    first_name = CharField(max_length=100, verbose_name="Фамилия")
    last_name = CharField(max_length=100, verbose_name="Имя")
    phone = CharField(
        max_length=12,
        unique=True,
        verbose_name="Телефон",
    )
    email = EmailField(unique=True, verbose_name="Email")
    advertisement = ForeignKey(
        Advertisement, verbose_name="Рекламная кампания", on_delete=DO_NOTHING
    )
    is_active = BooleanField(default=0, verbose_name="Активен")
    archived = BooleanField(default=0, verbose_name="В архиве")

    def __str__(self):
        return f"Lead {self.first_name!r} {self.last_name!r}"

apps/lead/forms.py
"""Модуль конструктор форм приложения lead"""

from django import forms
from apps.lead.models import Lead


class LeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ["first_name", "last_name", "phone", "email", "advertisement"]

apps/lead/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import (
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
    ListView,
)

from apps.lead.forms import LeadForm
from apps.lead.models import Lead


class LeadView(View):
    queryset = Lead.objects.select_related("advertisement")
    context_object_name = "lead"

    def check_permission(self, codename):
        if self.request.user.is_superuser:
            return True
        return any(
            permission.codename == codename
            for permission in self.request.user.permissions
        )


class LeadCreateView(LeadView, CreateView):
    form_class = LeadForm
    template_name = "lead/lead_create.html"

    def get_success_url(self):
        return reverse(
            "lead:lead_read",
            kwargs={"pk": self.object.pk},
        )


class LeadReadView(LeadView, DetailView):
    template_name_suffix = "_read"


class LeadUpdateView(LeadView, UpdateView):
    success_url = reverse_lazy("lead:lead_read")
    template_name_suffix = "_update"
    form_class = LeadForm

    def get_success_url(self):
        return reverse(
            "lead:lead_read",
            kwargs={"pk": self.object.pk},
        )


class LeadDeleteView(LeadView, DeleteView):
    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)

    def get_success_url(self):
        return reverse(
            "lead:lead_list",
        )


class LeadListView(LeadView, ListView):
    queryset = Lead.objects.filter(archived=False).only("last_name", "first_name")

    context_object_name = "leads"

templates/lead/lead_confirm_delete.html
{% extends 'core/_base.html' %}


{% block content %}
<h2 class="fw-bold">Действительно хотите удалить лида: {{ lead.first_name }} {{ lead.last_name }}?</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <p class="card-text">{{ lead.first_name }} {{ lead.last_name }}</p>
    <p class="card-text">{{ lead.email }}</p>
    <p class="card-text">{{ lead.advertisement.name }}</p>
    <div class="col">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Удалить лида</button>
        </form>
    </div>
</div>
<div class="col">
    <a href="{% url 'lead:lead_read' pk=lead.pk %}" class="btn btn-primary"
    >К Услуге</a>
</div>
<div class="col">
    <a href="{% url 'lead:lead_list' %}" class="btn btn-primary"
    >К списку услуг</a>
</div>
{% endblock %}

templates/lead/lead_create.html
{% extends "core/_base.html" %}

{% block content %}
<h2 class="fw-bold">Создание лида</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Создать</button>
        </form>
    </div>
    <div class="col"></div>
</div>
<a href="{%url 'lead:lead_list'%}" class="btn btn-primary">К списку лидов</a>

{% endblock %}

templates/lead/lead_delete.html
{% extends "core/_base.html" %}

{% block content %}
<h2 class="fw-bold">Удаление лида</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <p>Вы уверены что хотите удалить "{{ object.last_name }} {{ object.first_name }}"?</p>
        <form method="POST" action="/leads/{{ object.pk }}/delete/">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

templates/lead/lead_list.html
{% extends "core/_base.html" %}

{% block content %}
<h2 class="fw-bold">Лиды</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="hstack gap-3 pb-4">
        <a href="{% url 'lead:lead_create' %}" class="btn btn-success p-2">Создать</a>
    </div>
    <div class="col">
        <ul class="list-group">
            {% for lead in leads %}
            <li class="list-group-item list-group-item-light d-flex justify-content-between">
                <a href="{% url 'lead:lead_read' pk=lead.pk %}" class="text-decoration-none link-dark">{{ lead.last_name }} {{ lead.first_name }}</a>
                <a href="{% url 'lead:lead_delete' pk=lead.pk %}" class="btn btn-danger">Удалить</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

templates/lead/lead_read.html
{% extends "core/_base.html" %}

{% block content %}
<h2 class="fw-bold">Детальная информация о лиде</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <div class="card border-dark shadow" style="background: #eee">
            <div class="card-body">
                <h5 class="card-title fw-bold">{{ lead.last_name }} {{ lead.first_name }}</h5>
                <p class="card-text">{{ lead.phone }}</p>
                <div class="d-flex justify-content-end fw-bold">{{ lead.email }}</div>
                <div class="d-flex justify-content-center fw-bold">
                    <a href="{% url 'lead:lead_update' pk=lead.pk %}" class="btn btn-primary">Редактировать</a>
                </div>
                <div class="d-flex justify-content-center fw-bold">
                <a href="{% url 'lead:lead_delete' pk=lead.pk %}" class="btn btn-danger">Удалить услугу</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
<a href="{%url 'lead:lead_list'%}" class="btn btn-primary">К списку лидов</a>

{% endblock %}

templates/lead/lead_update.html
{% extends "core/_base.html" %}

{% block content %}
<h2 class="fw-bold">Редактирование лида</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST" >
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Применить</button>
        </form>
    </div>
    <div class="col"></div>
</div>
<a href="{%url 'lead:lead_read' pk=lead.pk %}" class="btn btn-primary">Сохранить без изменений</a>
<a href="{%url 'lead:lead_list'%}" class="btn btn-primary">К списку лидов</a>

{% endblock %}